spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fornecedor
      username: root
      password: vs368797
   jpa:
      hibernate.ddl-auto: update
      show-sql: true
